secret_token: ba8fbdd88e3e285b11117f25d0b8043b2b3ecd6a242db0331d8a09e4aa20c57d1c1af95b651d8046438f22d3804cf799408d04622d221cbd7264a725c7e9986c
devise_secret_key: 6712c57d6f8762ce9d730e4740721efa9b448711ecac9a04afcac277780ba9ed3cb30e3955e9c0f5a57ba88d59639f2d2c500e73f8c599b239ef70f6c0363028
devise_email: please-change-me-at-config-settings-yml@example.com
whitelisted_hosts:
  - .instedd.org
google:
  client_id:
  client_secret:
